Vagrant.configure("2") do |config|
    config.vm.define "cprojeanS" do |control|
        control.vm.box = "bento/ubuntu-24.04"
        control.vm.host_name = "cprojeanS"
        control.vm.network "private_network", ip: "192.168.56.110"
        control.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.cpus = 2
            vb.name = "cprojeanS"
        end
        control.vm.provision "shell", path: "scripts/server.sh"
    end
end