Vagrant.configure("2") do |config|
  # ================================= Server ==================================
  config.vm.define "cllovioS" do |server|
    server.vm.hostname = "cllovioS"

    # Box settings
    server.vm.box = "bento/debian-13"
    
    # Provider settings
    server.vm.provider "virtualbox" do |vb|
      vb.name = "cllovioS"
      vb.memory = 2048
      vb.cpus = 2
    end
    
    # Network settings
    server.vm.network "private_network", ip: "192.168.56.110"
    
    # Provision settings
    server.vm.provision "shell", path:"scripts/server-provision.sh", args: ["192.168.56.110"]
  end
end