Vagrant.configure("2") do |config|
# ================================= Server ==================================
    config.vm.define "cprojeanS" do |control|
        control.vm.host_name = "cprojeanS"
        
        # Box settings
        control.vm.box = "bento/debian-13"

        # Provider settings
        control.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.cpus = 2
            vb.name = "cprojeanS"
        end

        # Network settings
        control.vm.network "private_network", ip: "192.168.56.110"
        
        # Provision settings
        control.vm.provision "shell", path: "scripts/server-provision.sh"
    end

# ============================== Server worker ==============================
    config.vm.define "cprojeanSW" do |control|
        control.vm.host_name = "cprojeanSW"
        
        # Box settings
        control.vm.box = "bento/debian-13"
        
        # Provider settings
        control.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = 1
            vb.name = "cprojeanSW"
        end
        
        # Network settings
        control.vm.network "private_network", ip: "192.168.56.111"
        
        # Provision settings
        control.vm.provision "shell", path: "scripts/worker-provision.sh", args: "192.168.56.110"
    end
end