# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config| # "2" = configuration version
  # Box settings
  config.vm.box = "bento/ubuntu-24.04"

  # Provider settings
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 512
    vb.cpus = 1
  end

  # Network settings
  config.vm.network "private_network", ip: "192.168.56.110"

  # Provision settings
  config.vm.provision "shell", path:"apache.sh"

end
