Vagrant.configure("2") do |config|

  # ================================= Server ==================================
  config.vm.define "cllovioS" do |server|
    server.vm.hostname = "cllovioS"

    # Box settings
    server.vm.box = "bento/ubuntu-24.04"
    
    # Provider settings
    server.vm.provider "virtualbox" do |vb|
      vb.name = "cllovioS"
      vb.memory = 2048
      vb.cpus = 2
    end
    
    # Network settings
    server.vm.network "private_network", ip: "192.168.56.110"
    
    # Provision settings
    server.vm.provision "shell", path:"scripts/server-provision.sh", args: ["192.168.56.110"]
  end

  # ============================== Server worker ==============================
  config.vm.define "cllovioSW" do |server_worker|
    server_worker.vm.hostname = "cllovioSW"
    
    # Box settings
    server_worker.vm.box = "bento/ubuntu-24.04"
    
    # Provider settings
    server_worker.vm.provider "virtualbox" do |vb|
      vb.name = "cllovioSW"
      vb.memory = 512
      vb.cpus = 1
    end
    
    # Network settings
    server_worker.vm.network "private_network", ip: "192.168.56.111"
    
    # Provision settings
    server_worker.vm.provision "shell", path:"scripts/server-worker-provision.sh", args: ["192.168.56.110", "192.168.56.111"]
  end
end
